name: "Post release"
on:
  release:
    types:
      - published

jobs:
  example:
    name: "Example"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: ref_name
        run: echo "ref_name=${{  github.ref_name }}"

      - name: github.ref
        run: echo "github.ref=${{  github.github.ref }}"

      - name: github.ref_type
        run: echo "github.ref_type=${{  github.github.ref_type }}"

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v6
#        with:
#          base: main
#          token: ${{ secrets.GITHUB_TOKEN }}
#          branch-suffix: timestamp
#          title: "docs: update assets"
#          delete-branch: true
