name: "Post release"
on:
  release:
    types:
      - published

jobs:
  example:
    name: "Example"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: ref_name
        run: echo "ref_name=${{  github.ref_name }}"

      - name: help
        run: cut --help

      - name: major.minor
        run: |
          major=cut -d '.' -f 1 <<< "${{  github.ref_name }}"
          minor=cut -d '.' -f 2 <<< "${{  github.ref_name }}"
          cp foo/bar.txt foo/${major}.${minor}.bar.json

      - name: check
        run: ls -alF foo

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v6
#        with:
#          base: main
#          token: ${{ secrets.GITHUB_TOKEN }}
#          branch-suffix: timestamp
#          title: "docs: update assets"
#          delete-branch: true
